[package]
name = "proto3-parser"
version = "0.1.0"
authors = ["zzzdong <kuwater@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.5"
pest = "2.0"
pest_derive = "2.0"
